### ISSUE TITLE
bug report: installation problem using "curl"

### ISSUE THREAD

**Issue by StoneMac65** [d1onys1us/stn#121]
I tried to install stn using :

`curl --proto '=https' --tlsv1.2 -LsSf https://github.com/d1onys1us/stn/releases/latest/download/stn-installer.sh | sh`

output:

```
~$ curl --proto '=https' --tlsv1.2 -LsSf https://github.com/d1onys1us/stn/releases/latest/download/stn-installer.sh | sh
downloading stn 0.1.39 x86_64-unknown-linux-gnu
installing to /home/user/.cargo/bin
  stn
everything's installed!

user@localserver:~$ stn install
stn: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

it actually did not  build it. Then I tried

`$ cargo install --force stn`

this time image was built

**Comment by StoneMac65** [comment]
I also tried installing openssl again just to make sure

`sudo apt-get install libssl-dev`

and  export the library path

`export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH`

still problem remained until I uesd Cargo install

**Comment by d1onys1us** [comment]
@StoneMac65 may i ask what operating system you are using? maybe i will need to compile a statically linked binary.

**Comment by StoneMac65** [comment]
@d1onys1us 

my os:

`Linux localserver 6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

It's interesting, I thought maybe I try it with root user(my first user is also in sudoers). its still the same

**Comment by d1onys1us** [comment]
> @d1onys1us
> 
> my os:
> 
> `Linux localserver 6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
> 
> It's interesting, I thought maybe I try it with root user(my first user is also in sudoers). its still the same

yeah that is interesting. i think i can fix it by building a statically linked binary.

is the tool working fine for you now after installing with cargo? i will work on pushing out a fix soon.

**Comment by StoneMac65** [comment]
Great. Looking forward to test new version

And yes. It worked fine after using cargo build. Installed a node in few seconds

**Comment by d1onys1us** [comment]
> same issue when running `stn install` on Ubuntu 22

for now i have updated the default installation method: https://github.com/d1onys1us/stn?tab=readme-ov-file#cargo-recommended

but will work on that static binary fix soon. looks like the build failed (ironically) on my ubuntu github runner.

**Comment by x777** [comment]
Got the same issues with stn on Ubuntu 22. But for now, I got the error after command `stn config full`:

```
Failed to initialize EnvManager: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by d1onys1us** [comment]
https://github.com/d1onys1us/stn/pull/144 fixed installation issues here.

@x777 could you please open a separate issue for your `stn config full` problem?
