### ISSUE TITLE
cargo install stn gives error

### ISSUE THREAD

**Issue by abbadmus** [d1onys1us/stn#141]
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `serde` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `proc-macro2` (build script) due to 1 previous error
error: could not compile `libc` (build script) due to 1 previous error
error: could not compile `libc` (build script) due to 1 previous error
error: could not compile `typenum` (build script) due to 1 previous error
error: failed to compile `stn v0.1.44`, intermediate artifacts can be found at `/tmp/cargo-installdVSn2Y`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by safeina86** [comment]
The error you're encountering indicates that the system is unable to find the C compiler (`cc`). The `cc` command is essential for compiling native code, and its absence can lead to build failures.

Here are some steps to resolve the issue:

1. **Install a C Compiler:**
   Ensure that you have a C compiler installed on your system. On Linux, you can typically install it using your package manager. For example, on Debian/Ubuntu-based systems, you can run:

   ```bash
   sudo apt-get update
   sudo apt-get install build-essential
   ```

   On macOS, you can install the Xcode Command Line Tools:

   ```bash
   xcode-select --install
   ```

   On Windows, you might need to install a compatible C compiler. You can use tools like MinGW or MSVC. Make sure to follow the instructions provided by the Rust documentation for setting up the build environment on Windows.

2. **Ensure C Compiler is in the PATH:**
   After installing the C compiler, make sure it is in your system's `PATH`. The Rust build system relies on finding the `cc` command in the `PATH`.

3. **Check Environment Variables:**
   Ensure that the environment variables required for building are properly set. This includes variables like `CC` and `CXX`. If they are not set, the build system will try to use the default compiler.

   You can set the `CC` variable explicitly before running `cargo install`:

   ```bash
   CC=gcc cargo install stn
   ```

4. **Update Rust and Cargo:**
   Ensure that you are using the latest versions of Rust and Cargo:

   ```bash
   rustup update
   ```

5. **Review Platform-specific Documentation:**
   Some platforms may have additional requirements for building native dependencies. Check the platform-specific documentation for Rust to ensure that you have met all the prerequisites.

6. **Check System Dependencies:**
   The `stn` crate may have dependencies on external libraries. Make sure you have the necessary development libraries installed on your system. Refer to the crate's documentation or repository for any specific requirements.

After performing these steps, try running the `cargo install stn` command again. If the issue persists, carefully review the error messages for any additional information, and consider checking the crate's GitHub repository or documentation for any reported issues or build instructions.

**Comment by safeina86** [comment]
Let me know if the problem is solved @abbadmus

**Comment by abbadmus** [comment]
I have it running thanks
